### ISSUE TITLE
Unable to build without ipv6

### ISSUE THREAD

**Issue by clochix** [bnjbvr/cozy-docker-dev#1]
By default, Ubuntu tries to use IPv6 to fetch package.
To force use of IPv4, you may need to add this line at the beginning of `Dockerfile`:

```
RUN echo 'Acquire::ForceIPv4 "true";' | tee /etc/apt/apt.conf.d/99force-ipv4
```

Should this be added to the README?

**Comment by bnjbvr** [comment]
Thank you. I've never noticed this and I'm using Ubuntu 15.10. Which version of Ubuntu do you use? Do you see any specific error message? I'd be good with adding this to the readme if we had a better idea of what the message is, or at least the symptoms.

**Comment by bnjbvr** [comment]
Fixed by your PR, cheers!
