### ISSUE TITLE
Ubuntu keyserver not found on build

### ISSUE THREAD

**Issue by Aryess** [bnjbvr/cozy-docker-dev#3]
Hey,

Finally got some time to try it out, but it fails on build on my Fedora machine.
Full log available [here](https://cozy.aryess.me/public/hastebin/AheNxsSd), but the important lines are:

```
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.02lIEEBw32 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys C300EE8C
gpg: requesting key C300EE8C from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
```

Possibly linked to the fact I'm on Fedora. Will gladly test any fix.

Cheers

**Comment by bnjbvr** [comment]
Hi!
The website looks up from here. Maybe it is that your docker instance being built has no external access to the Internet? I am not too sure here...
@jankeromnes, does this look familiar to you? This happens when building an instance.

**Comment by bnjbvr** [comment]
@Aryess, out of curiosity, does the fix just merged to the README helps in any way?

**Comment by Aryess** [comment]
@bnjbvr Uh, the build.sh instead of sync.sh? If yes, that's already what I was doing

**Comment by Aryess** [comment]
Nevermind. Looks like my docker is off network, as you pointed out... I'll try to fix that first and come back to Cozy :)
